### ISSUE TITLE
FDND Semester pagina component checklist

### ISSUE THREAD

**Issue by KaanKalmi** [KaanKalmi/dont-repeat-yourself-component-library#49]
## Components list sprint view:
- [x]  HvA logo
- [x]  [FDND Button](https://github.com/KaanKalmi/dont-repeat-yourself-component-library/issues/4)
- [x]  [Sprint button](https://github.com/KaanKalmi/dont-repeat-yourself-component-library/issues/5)
- [x] #50
- [x] #51
- [x] #8 
- [x]  [Footer component](https://github.com/KaanKalmi/dont-repeat-yourself-component-library/issues/12)
